### PR TITLE
Improve config management strategy document

### PR DESCRIPTION
**Pull request by danieldreier**
I started this as a long message on issue #50 and in an email to @seancribbs but realized it would be more constructive to make a PR.

A few other notes:

- The term "Riak automation levels (RAL)" is confusing because puppet has the Resource Abstraction Layer (RAL) as a core concept.
- Anything (e.g. Riak EE) that requires arbitrary downloads from S3 outside of the context of package management is really annoying. The right place to solve this is by distributing using a package repository, not by requiring that the config management tool re-implement that functionality. You *can* do it in puppet if necessary, but it's pretty un-idiomatic, and I generally steer clear of Puppet modules that do it.
- Distributing patches as separate files (in a basho-patches directory) also seems weird to me; I'd expect that to be a regular system package update. As far as I understand the requirement, this duplicates the functionality of apt or yum in a config management tool. I think that this will introduce needless complexity because there's an abstraction layer violation in using system packages and unpackaged out-of-band patches together.

That said, I realize that I'm not likely to get changes made to how you package/distribute Riak / Riak EE / patches; I'm sure there's plenty of path dependency on the current approach by now. I just want to make clear that moves complexity from the packaging side to the CM side.

I'm happy to see this document and I feel like it sets some clear objectives that facilitate module development. If I've inadvertently made any of this too Puppet-centric, I didn't intend it - I just lack experience with Chef and Ansible. I'm open to any changes, or to closing this PR entirely if it's off-base from what the rest of the community is looking for.

### CODE REVIEW

**Comment by seancribbs** [comment]
Not sure what I have to do with this, but I can address the purpose of the `basho-patches` directory, which is two-fold:

1. We must sometimes provide updated modules that override the Erlang standard library (or more rarely, a third party dependency). This directory is the most direct way to do so.
2. We must sometimes provide patches to customers or the community on a timetable that is shorter than our normal release cycle. This is very rare for the open-source version, except in the case of security vulnerabilities. Customers who receive patches are directly helped by support engineers to manage said patches.

It sounds like this document needs some internal review.

**Comment by danieldreier** [comment]
@seancribbs I spaced out and ping'd you incorrectly - got names mixed up - sorry about that. I meant to ping @mjbrender. I do appreciate the explanation. That does help explain why using that directory outside of packaging is expedient. I'm sure you've all put more thought into this problem than I have - I know it's frustrating when outsiders with limited information second-guess these sorts of trade-offs.

I just tend to be skeptical of anything outside of normal system packaging, because it makes deployment and config management a lot more complicated. I've seen a lot of really ugly hacks in puppet modules to get around this sort of thing, so if it's possible to fix it up-front in packaging it makes automating things much easier. For example, if patches need to be deleted when a point release comes out that incorporates the patch, the module will need to purge old patches, which implies tracking state on which downloaded URL created which file; that starts re-implementing dpkg/rpm in a really awkward way.

This may be naive - I don't know the history of discussion of this problem - but it seems to me the most straightforward would be to have distribute riak-patches packages via package repositories that drop such files in the right place. That would allow for distribution without touching the main riak package, but the riak-patches package could have dependencies on specific riak and erlang versions; when a riak point release negates the need for a patch, the newer version of the patch package would remove the unneeded files. Upgrading the riak package would implicitly upgrade the patches package, keeping all the complexity managed by a package management system that's intended to do that rather than re-implementing it with zip files and config management. FWIW, [FPM](https://github.com/jordansissel/fpm) is my preferred way to build simple packages quickly.

You could probably even distribute your out-of-band patches for enterprise customers that way; FPM makes package building about as hard as building tarballs. On both rpm and dpkg, setting the "provides" metadata allows you to obsolete a package, so if you track which patch packages you issue you could use that to formally make the next riak release the upgrade path for each patch package, causing the patches to be cleaned up during the upgrade process.

I hope this doesn't come off as back-seat release engineering. I get that there may be totally legitimate (or unfortunate but pragmatic) reasons why this isn't feasible and why a config management system needs to arbitrarily drop files into an updates folder.

**Comment by seancribbs** [comment]
@danieldreier You raise valid concerns. And I agree, that patch directory should only be used in extenuating circumstances. 

I also agree that users should install from binary packaging provided by Basho. In some cases (Riak EE), that involves downloading from a secret/authenticated URL, but open-source is all available on our packagecloud.io repository.  The ability for an automation script to build from source is no longer necessary, and especially not recommended given that we often require custom builds of Erlang that are not from Ericsson. It's difficult enough for our engineers to be building on the right version, let alone the community.

**Comment by mjbrender** [comment]
@danieldreier this PR is fantastic. While some details may need to shift going forward, the added clarity is well worth a merge. @seancribbs, please feel free to pull me and @seemaj in to a mumble. Speaking of her, @seemaj - check this out ^^^ :+1:

**Pull request merged**
